### ISSUE TITLE
StaticLoggerBinder

### ISSUE THREAD

**Issue by ghost** [yakivyusin/SimpleNetNlp#10]
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

Although not a bug in the c# code, this is a frustrating error which causes the instantiation of Sentence to be slower than required and is thrown for every new Sentence created.

Is there a workaround or means to suppress?

**Comment by sssibo** [comment]
Good day, did you get this fixed? If yes how was it done?
