### ISSUE TITLE
Consider supporting German

### ISSUE THREAD

**Issue by GeorgeS2019** [yakivyusin/SimpleNetNlp#26]
@yakivyusin 

We have many Ukraine in Germany. 

They are having challenges to really speaking German with more confidence.

I am writing app for that and it would be great you tool help the Ukrainians in Germany by using this project to support German too :-)

I have tested 4.5.6 using the latest ikvm.maver with the [**German** language model](https://github.com/NightOwl888/lucenenet-opennlp-mavenreference-demo/issues/1#issuecomment-1971460883)

It would be great that we have a wrapper through your work here to make it easy to access the Standford CoreNLP API for German

**Comment by yakivyusin** [comment]
Hello @GeorgeS2019 

Yeah, I already have the issue for other languages support: #17 . German will be the first priority among them.
