### ISSUE TITLE
bin/edu folder not getting creating

### ISSUE THREAD

**Issue by sandeep1756** [yakivyusin/SimpleNetNlp#3]
Hi
When deploying to app services on azure, the edu folder with relevant tagger and tagger-property files are not getting created in bin folder and to me that seems to be the reason this is not working when deployed. Dev env works perfectly. The Nuget package shows to have successfully installed. Can you suggest what could be reason for this.

Thanks.

**Comment by yakivyusin** [comment]
Hi!

This question is often asked. Basicly, model packages is run (and copy files) by MSBuild when you build your application.
For other scenarios (example Azure) you can try this solution: https://github.com/yakivyusin/SimpleNetNlp/issues/2#issuecomment-375061285 or you can manually copy `edu` folder from dev build.

**Comment by sandeep1756** [comment]
Hey thanks for responding. Yes for now, we copied the edu folder to bin to get it working. Didn't saw this already answered in other comment as highlighted by you.
Thanks again.
