### ISSUE TITLE
IOException when using OpenIE

### ISSUE THREAD

**Issue by felinepunch** [yakivyusin/SimpleNetNlp#4]
using Microsoft.VisualStudio.TestTools.UnitTesting;
using SimpleNetNlp;

namespace StanfordNLPTest
{
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
            var sentence = new Sentence("She born in a small town.");
            var lemmas = sentence.Lemmas;
            var pos = sentence.PosTags;
            var triplets = sentence.OpenIe;
        }
    }
}

SimpleNetNlp.Exceptions.UnhandledLibraryException: An unexpected exception was thrown by Stanford CoreNLP ---> edu.stanford.nlp.io.RuntimeIOException: Could not load affinity model at edu/stanford/nlp/models/naturalli/affinities: Unable to open "edu/stanford/nlp/models/naturalli/affinities/pp.tab.gz" as class path, filename or URL

It works well at POS taggting line. But OpenIe called, It hangs a minute and throws exception.

**Comment by yakivyusin** [comment]
Hi!

Do you have installed `SimpleNetNlp.Models.Naturalli` package?

UPD: Thank you for your report! I found an error in build script of `SimpleNetNlp.Models.Naturalli` package. It will be fixed soon.

**Comment by yakivyusin** [comment]
Package `SimpleNetNlp.Models.Naturalli` was updated to 3.8.0.1 release. In this version, this bug has to be fixed.
Try to update `SimpleNetNlp.Models.Naturalli` package and please leave comment if this helped.

**Comment by felinepunch** [comment]
IOException is not throw. Thanks yakivyusin.
